# netlify.toml - Fixed configuration
[build]
  # Simple build command
  command = "echo 'Build complete - functions ready'"
  
  # Directory to publish (for static files)
  publish = "public"
  
  # Functions directory
  functions = "netlify/functions"

# Function configuration
[functions]
  # Increase timeout for all functions
  "*" = { timeout = 30 }

# API routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
